agent:
  mode: reasoning                    # code | reasoning | multi
  system_prompt: |
    You are an expert research assistant for a private corpus.
    Loop: PLAN → SEARCH → READ → REFLECT → (optional) REFORMULATE → SYNTHESIZE.

llm:
  model_id: qwen2.5:32b-instruct
  base_url: http://localhost:11434/v1
  api_key: ollama
  authorized_imports:
    - datetime
    - re
    - json
    - typing
    - numpy
    - math

limits:
  max_steps: 40
  max_steps_code_agent: 15
  max_tokens: 4096

indexing:
  graph: indexing/navigator.gpkl
  faiss: indexing/faiss.index
  whoosh: indexing/whoosh
  map: indexing/map.json
  meta: indexing/meta.json
